#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"
#include "HelperFunction.ush"

float3 TargetColor;

Texture2D<float4> SceneColorTexture;

float4 MainPS(float4 SvPosition : SV_POSITION) : SV_Target0
{
	const float3 TargetColorLab = RGBtoLab(TargetColor);

	const float4 SceneColor = SceneColorTexture.Load(int3(SvPosition.xy, 0));
	
#if USE_UNLIT_SCENE_COLOR
	FScreenSpaceData ScreenSpaceData = GetScreenSpaceDataUint(SvPosition.xy, false);
	const float4 SceneColorUnlit = float4(ScreenSpaceData.GBuffer.BaseColor, 0);
	const float3 SceneColorLab = RGBtoLab(SceneColorUnlit.rgb);
#else
	const float3 SceneColorLab = RGBtoLab(SceneColor.rgb);
#endif

	static const uint QuantizationLevels = 10;  // 每通道分10级
	static const float QuantizationStep = 1.0 / float(QuantizationLevels);

	// 高效量化运算（无分支）
	float3 quantizedLab = floor(SceneColor.rgb * QuantizationLevels) * QuantizationStep;
	
	
	const float DeltaE = DeltaE2000(TargetColorLab, SceneColorLab, 1, 1, 1);
	
	// If the scene is within the threshold, return scene colour
	// 	Delta E	Perception
	// <= 1.0	Not perceptible by human eyes.
	// 1 - 2	Perceptible through close observation.
	// 2 - 10	Perceptible at a glance.
	// 11 - 49	Colors are more similar than opposite
	// 100	Colors are exact opposite
	FLATTEN
	if(DeltaE < 45)
	{
		return SceneColor;
	}
	
	// Otherwise return greyscale version of scene colour
	return 0.21 * SceneColor.r + 0.72 * SceneColor.g + 0.07 * SceneColor.b; 
}